FROM ubuntu
ARG DEBIAN_FRONTEND=noninteractive
RUN apt -yqq update
WORKDIR /usr/src/app

## GIT
RUN apt-get install git -y
RUN apt-get install npm -y
RUN ls
RUN git clone https://github.com/michelpl/ecommerce-discount-client.git .
RUN npm install --production
CMD [ "node", "src/index.js" ]




